[PUSH_H_72]   	  	   
[PRINT_H]	
  [PUSH_e_101]   		  	 	
[PRINT_e]	
  [PUSH_l_108]   		 		  
[PRINT_l]	
  [PUSH_l_108]   		 		  
[PRINT_l]	
  [PUSH_o_111]   		 				
[PRINT_o]	
  [PUSH_SPACE_32]   	     
[PRINT_SPACE]	
  [PUSH_W_87]   	 	 			
[PRINT_W]	
  [PUSH_o_111]   		 				
[PRINT_o]	
  [PUSH_r_114]   			  	 
[PRINT_r]	
  [PUSH_l_108]   		 		  
[PRINT_l]	
  [PUSH_d_100]   		  	  
[PRINT_d]	
  [PUSH_!_33]   	    	
[PRINT_!]	
  [END]


